name: Build Admin

on:
  push:
    tags:
      - "v4.*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        path: "app/sources"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'app/sources/admin/package-lock.json'
    - run: npm install --prefix=app/sources/admin
    - run: npm run build --prefix=app/sources/admin
    - uses: actions/upload-artifact@master
      with:
        name: buildfiles
        path: deploy/admin


  release:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@master
        with:
          name: buildfiles
          path: ./build

      - name: archive
        run: cd ./build && zip vi-admin.zip -r ./*

      - name: Get version from tag
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/vi-admin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


